#Github Workflow Mypy check
#
#SPDX-FileCopyrightText: 2020 IntelMQ Team
#SPDX-License-Identifier: AGPL-3.0-or-later

name: "Mypy typecheck"

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install mypy
    - name: Static type checking with mypy
      run: |
        mypy --config-file=mypy.ini
